### ISSUE TITLE
After installing awsets, it does not work as a command.

### ISSUE THREAD

**Issue by rahul-karav** [trek10inc/awsets#1]
After installing GO and then awsets, it does not work as a command.
`GO111MODULE="on" go get github.com/trek10inc/awsets/cmd/awsets`
Is there another step before we can run it as a command?

```
❯ GO111MODULE="on" go get github.com/trek10inc/awsets/cmd/awsets
go: github.com/trek10inc/awsets/cmd/awsets upgrade => v0.0.0-20200903202143-ec27b76811e6
```
```
❯ awsets --help
zsh: command not found: awsets
```

**Comment by jcarter3** [comment]
It sounds ~/go/bin isn't a part of your PATH. Did that step get missed on https://golang.org/doc/install?

**Comment by jcarter3** [comment]
Closing from lack of activity - if this is still an issue, please re-open
