### ISSUE TITLE
DynamoDB backups of deleted tables excluded

### ISSUE THREAD

**Issue by ryansb** [trek10inc/awsets#15]
First, thanks for adding DDB backups to 0.6.1. 

Commit [0925415...](https://github.com/trek10inc/awsets/commit/09254152ae47e860b0f0f5e4548ab77452644013) / issue #14 added DDB backups as sub-resources to `ddb/table`. DynamoDB backups can exist of now-deleted tables that still need to be cleaned up. 

To gather those, I think there needs to be a separate resource type `ddb/backup` added instead of backups being a sub-resource listed on existing tables. Another option would be to make a fake `ddb/table` resource with a status of `DELETED` and put those backups as sub-resources of.

**Comment by jcarter3** [comment]
Ah, makes sense. I think moving ddb/backup to a separate resource type makes the most sense. It'd add a relation back to a potentially nonexistent table, but that should be fine? That is currently how RDS backups are handled (relationship goes to a non-existent database). I'll get that updated.

**Comment by jcarter3** [comment]
This should be fixed in the latest version. Let me know if it's still not correct

**Comment by ryansb** [comment]
Yeah that works perfectly! Having a semi-empty relationship when the DDB table is gone but backups still exist makes sense, since they really are orphaned resources.
