### ISSUE TITLE
Bug: Listers returning data from wrong services.

### ISSUE THREAD

**Issue by jspreddy** [trek10inc/awsets#22]
## Bug:
The following Listers returned data from rds and are "Type"ing as their own.

1. docdb/cluster
2. docdb/instance
3. neptune/dbcluster
4. neptune/dbclustersnapshot
5. neptune/dbinstance

## Details
- I do not have any docdb clusters. 
- Listing for `docdb/cluster` returns data. 
- These records indicate that the resources are of `"Type": "docdb/cluster"`. 
- The rest of that record contains values from rds clusters. [Account, Region, Id, Name, Attributes, Tags, Relations]
- Same thing happens with above Listers. i.e. They are returning `rds/*` resource information and are "Type"ing as their own.
- This may be happening with other listers. This is just what I ran into.

## command ran:

```bash
awsets list --profile "my-profile" --show-progress --regions "us-east-1" --include "docdb" --output "docdb-output.json"
awsets list --profile "my-profile" --show-progress --regions "us-east-1" --include "neptune" --output "neptune-output.json"
```

## Version

```
awsets - version: 1.0.4	commit: ba77e77d0c6b00fbdd59712a0b4d08c49f2d9b61	date: 2021-12-10T17:21:29Z
```

**Comment by jcarter3** [comment]
:thinking: this is pretty strange. I was able to replicate this with raw `aws cli` calls as well, so it seems that AWS themselves returns RDS instances for these lists. Let me experiment some more and see if I can figure out why they do that.

For example - I ran `aws docdb describe-db-instances --region us-east-1` and received all my Postgres RDS instances.

**Comment by jcarter3** [comment]
I found this: https://github.com/aws/aws-cli/issues/4688
Seems to be an AWS bug they won't fix. I'll check if I can reliably filter these out somehow.

**Comment by jspreddy** [comment]
haha.. the classic "It's a feature, not a bug!" response from AWS. 🤦

**Comment by jspreddy** [comment]
Thanks for looking into a workaround. Really appreciate it.

**Comment by jcarter3** [comment]
This should be fixed in v1.0.6, please update and check

**Comment by juarezjsonar** [comment]
@jcarter3 Tried on versions `1.22.11` and `2.5.3`. None have the fix.
Side note: No, I didn't try it on 1.0.6

**Comment by jcarter3** [comment]
Are you referring to AWS cli versions? Awsets only goes to 1.0.6. AWS does not consider this a bug, but i was able to filter them out in awsets
