### ISSUE TITLE
Distribution via brew once we have a 1.0.0

### ISSUE THREAD

**Issue by dgomesbr** [trek10inc/awsets#4]
Hello, 

Would be great to be able to do `brew install awssets`. Once this reaches 1.0.0 or when you have time, would you mind updating the distribution mechanism to `brew` for Mac binaries?

ref: https://medium.com/@ben.lafferty/deploying-go-cli-applications-316e9cca16a4

**Comment by jcarter3** [comment]
GoReleaser does make this pretty easy! It should be set up now.
